# Server
server.port=8080

# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d73b0gk2kvos738bojp0-a.oregon-postgres.render.com:5432/expense_tracker_1tcm
spring.datasource.username=expense_tracker_1tcm_user
spring.datasource.password=nbqu3IU18l4lKJFVxvIc0uFRAj3DoBDp
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=MyVerySecretKeyForExpenseOSApplication2024SuperSecureBase64Encoded
app.jwt.expiration-ms=86400000

# CORS (IMPORTANT → replace with your Vercel URL)
app.cors.allowed-origins=https://expense-front-end-lsgy.vercel.app

# Logging
logging.level.com.expenseos=DEBUG
logging.level.org.springframework.security=WARN
